In [7]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import seaborn as sns

In [8]:
data = pd.read_csv("PlayTennis.csv")
data.head()

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes
3      Rain        Mild     High    Weak         Yes
4      Rain        Cool   Normal    Weak         Yes

In [9]:
from sklearn.preprocessing import OrdinalEncoder
outlook_encoder = OrdinalEncoder()
data['Outlook'] = outlook_encoder. fit_transform(data[['Outlook']])

temp_encoder = OrdinalEncoder()
data['Temperature' ] = temp_encoder. fit_transform(data[['Temperature' ]])

humid_encoder = OrdinalEncoder()
data['Humidity'] = humid_encoder.fit_transform(data[['Humidity']])

wind_encoder = OrdinalEncoder()
data['Wind'] = wind_encoder. fit_transform(data[['Wind' ]])

play_encoder = OrdinalEncoder()
data['Play Tennis' ] = play_encoder.fit_transform(data[['Play Tennis']])

In [10]:
data.head()

   Outlook  Temperature  Humidity  Wind  Play Tennis
0      2.0          1.0       0.0   1.0          0.0
1      2.0          1.0       0.0   0.0          0.0
2      0.0          1.0       0.0   1.0          1.0
3      1.0          2.0       0.0   1.0          1.0
4      1.0          0.0       1.0   1.0          1.0

In [11]:
x = data.drop('Play Tennis', axis=1)
y = data['Play Tennis']

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x,y , test_size=0.2, random_state=20 )